source 'http://rubygems.org'

gem 'cucumber'
gem 'json'
gem 'cuke_sniffer'
gem 'httparty'
gem 'parallel_cucumber'
gem 'rake'
gem 'rubocop'
gem 'colorize'
gem 'minitest'
gem 'byebug'
gem 'google-api-client'
gem 'google-cloud-bigquery'
gem 'google-cloud-storage'
